before_cache:
  - |
    if command -v cargo; then
      if ! command -v cargo-sweep; then
        cargo install cargo-sweep
      fi
      cargo sweep -i
      cargo sweep -t 15
    fi
  - rm -rf ~/.cargo/registry/src

matrix:
  fast_finish: true
  include:
    - name: Run Rust tests(linux)
      language: rust
      os: linux
      rust: stable
      cache: cargo
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
      env:
        # Prevention of cache corruption.
        # See: https://docs.travis-ci.com/user/caching/#caches-and-build-matrices
        - JOBCACHE=1

    - name: Run Rust tests(osx)
      language: rust
      os: osx
      rust: stable
      cache: cargo
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
      env:
        # Prevention of cache corruption.
        # See: https://docs.travis-ci.com/user/caching/#caches-and-build-matrices
        - JOBCACHE=11
