[package]
name = "py-binding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hessian_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.3"

[dependencies.hessian_rs]
path = "../hessian"